# Project-wide Gradle settings.
# For more details on how to configure your build, see
# http://www.gradle.org/docs/current/userguide/build_environment.html

# AndroidX libraries use this property to determine if they should use AndroidX.
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Non-transitive R classes for faster builds
android.nonTransitiveRClass=true

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
